### ISSUE TITLE
Replace List and Map with StorageMap.

### ISSUE THREAD

**Issue by hurui200320** [NekoHitDev/Ritmin#24]
We are storing purchase records and milestones as Map<Hash160, Integer> and List<WCAMilestone>.

When we need to add a new purchase record or update a milestone, we need to rewrite the whole map and list, which is 75% * length of all bytes * unit price (0.001GAS for now). If we have a million purchases, each Map entry takes 20 (Hash160) + 4 (Integer) bytes, then it is still a lot. No one likes that.

So I'm wondering if we can replace those maps and lists with StorageMap, which only cares about the key we indexed. But this required a fundamental change to the data structure.

The storage map limits the key to 64Bytes max. And we need a prefix to identify different maps. I want to set up different maps based on the content. Instead of using the identifier as the key of WCA, I want to replace that with sha256(Creator's Hash160 + identifier). For this case, the identifier becomes the title of WCA. That sha256 (Hash256) is the `id` of this WCA.

For Static content. Like title, description, milestone descriptor of a WCA, those are write-once-read-many. So we can package them into one giant object and store them in a map. According to the documentation, read from storage should cost no GAS, and the `deserialize` method has a fixed GAS usage no matter how big our content is.

For dynamic content, like the status of WCA, this will be updated on every potential writing request. So let's pack them into an object and try to keep it as small as possible.

For purchase records, use a StorageMap to represent, the key is `[Map prefix][WCA id][Buyer's Hash160]`, the content is the amount, just like the token contract.

For milestones, only proof-of-work is needed to be rewritten, so we can set up a StorageMap. The key is `[Map prefix][WCA id][milestone index]`.

Storage maps are look like this:

![photo_2021-08-18_16-46-52](https://user-images.githubusercontent.com/8587572/129867940-63ad1c6e-70b9-4e09-9e77-7bfe45716338.jpg)

Two bytes (two English char) for map prefix, 32Bytes for WCA id, which is the sha256 of owner hash160 and title/identifier. Then 20Bytes for buyer's Hash160, or some bytes for an integer.

This is just a rough idea, I will try to implement those in code and have a test.

**Comment by ykoitzsch** [comment]
good idea, this way the contract can scale without it increasing in GAS for anyone (except the creator will have initially more GAS costs because it needs to write into more maps or am I mistaken?)
so far I don't see any issue with your concept 👍
